const SPRITE_SIZE = 102;

const FRAMES_COUNT_APPEAR = 60;
const FRAMES_COUNT_TOTAL = 90;
const FRAME_RATE = 2;

const TOTAL_IMAGES = 1;//10;//13;

const MILISECONDS_IN_SECOND = 1000;
const SECONDS_IN_MINUTE = 60;
const SECONDS_IN_HOUR = 3600;