const SPRITE_SIZE = 102;

const FRAMES_COUNT_APPEAR = 48;
const FRAMES_COUNT_TOTAL = 72;
const FRAME_RATE = 1;

const TOTAL_IMAGES = 10;//13;

const MILISECONDS_IN_SECOND = 1000;
const SECONDS_IN_MINUTE = 60;
const SECONDS_IN_HOUR = 3600;